name: flutterprojectsetup
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  get: ^4.6.1
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  connectivity: ^3.0.6
  http: ^0.13.4
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0
  dotted_line: ^3.1.0
  action_slider: ^0.6.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
#  dart_code_metrics: ^4.12.0
  get_it: ^7.2.0
  intl: ^0.17.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/png/ic_launcher.png"



dependency_overrides:
  platform: ^3.1.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/gif/

  fonts:
    - family: ProzaLibre
      fonts:
        - asset: assets/fonts/ProzaLibre_Regular.ttf
        - asset: assets/fonts/ProzaLibre_Bold.ttf
        - asset: assets/fonts/ProzaLibre_SemiBold.ttf
          weight: 600
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Regular.ttf
        - asset: assets/fonts/OpenSans_SemiBold.ttf
          weight: 600
